/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUnhandledExceptionModelFromDiscriminatorValue, createUserExistsModelFromDiscriminatorValue, createUserModelFromDiscriminatorValue, serializeRegisterAccountModel, serializeUserModel, type RegisterAccountModel, type UnhandledExceptionModel, type UserExistsModel, type UserModel } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /accounts/register
 */
export interface RegisterRequestBuilder extends BaseRequestBuilder<RegisterRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserModel>}
     * @throws {UserExistsModel} error when the service returns a 409 status code
     * @throws {UnhandledExceptionModel} error when the service returns a 500 status code
     */
     post(body: RegisterAccountModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UserModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: RegisterAccountModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RegisterRequestBuilderUriTemplate = "{+baseurl}/accounts/register";
/**
 * Metadata for all the requests in the request builder.
 */
export const RegisterRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RegisterRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createUserExistsModelFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createUnhandledExceptionModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeRegisterAccountModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
