services:
  frontend:
    build: .
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./:/app:z
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BASE_URL=/ticket-tracer-web/