/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AccountsRequestBuilderNavigationMetadata, type AccountsRequestBuilder } from './accounts/index.js';
// @ts-ignore
import { BoardsRequestBuilderNavigationMetadata, BoardsRequestBuilderRequestsMetadata, type BoardsRequestBuilder } from './boards/index.js';
// @ts-ignore
import { ProjectsRequestBuilderNavigationMetadata, ProjectsRequestBuilderRequestsMetadata, type ProjectsRequestBuilder } from './projects/index.js';
// @ts-ignore
import { TicketsRequestBuilderNavigationMetadata, TicketsRequestBuilderRequestsMetadata, type TicketsRequestBuilder } from './tickets/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata } from './users/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';
// @ts-ignore
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
// @ts-ignore
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
// @ts-ignore
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
// @ts-ignore
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * Instantiates a new {@link TicketTracerApiClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createTicketTracerApiClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    let serializationWriterFactory : SerializationWriterFactoryRegistry
    let parseNodeFactoryRegistry : ParseNodeFactoryRegistry
    
    if (requestAdapter.getParseNodeFactory() instanceof ParseNodeFactoryRegistry) {
        parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry
    } else {
        throw new Error("requestAdapter.getParseNodeFactory() is not a ParseNodeFactoryRegistry")
    }
    
    if (requestAdapter.getSerializationWriterFactory() instanceof SerializationWriterFactoryRegistry) {
        serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry
    } else {
        throw new Error("requestAdapter.getSerializationWriterFactory() is not a SerializationWriterFactoryRegistry")
    }
    
    serializationWriterFactory.registerDefaultSerializer(JsonSerializationWriterFactory);
    serializationWriterFactory.registerDefaultSerializer(TextSerializationWriterFactory);
    serializationWriterFactory.registerDefaultSerializer(FormSerializationWriterFactory);
    serializationWriterFactory.registerDefaultSerializer(MultipartSerializationWriterFactory);
    
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    parseNodeFactoryRegistry.registerDefaultDeserializer(JsonParseNodeFactory, backingStoreFactory);
    parseNodeFactoryRegistry.registerDefaultDeserializer(TextParseNodeFactory, backingStoreFactory);
    parseNodeFactoryRegistry.registerDefaultDeserializer(FormParseNodeFactory, backingStoreFactory);
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<TicketTracerApiClient>(requestAdapter, pathParameters, TicketTracerApiClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface TicketTracerApiClient extends BaseRequestBuilder<TicketTracerApiClient> {
    /**
     * The accounts property
     */
    get accounts(): AccountsRequestBuilder;
    /**
     * The boards property
     */
    get boards(): BoardsRequestBuilder;
    /**
     * The projects property
     */
    get projects(): ProjectsRequestBuilder;
    /**
     * The tickets property
     */
    get tickets(): TicketsRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TicketTracerApiClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TicketTracerApiClientNavigationMetadata: Record<Exclude<keyof TicketTracerApiClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    accounts: {
        navigationMetadata: AccountsRequestBuilderNavigationMetadata,
    },
    boards: {
        requestsMetadata: BoardsRequestBuilderRequestsMetadata,
        navigationMetadata: BoardsRequestBuilderNavigationMetadata,
    },
    projects: {
        requestsMetadata: ProjectsRequestBuilderRequestsMetadata,
        navigationMetadata: ProjectsRequestBuilderNavigationMetadata,
    },
    tickets: {
        requestsMetadata: TicketsRequestBuilderRequestsMetadata,
        navigationMetadata: TicketsRequestBuilderNavigationMetadata,
    },
    users: {
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
