/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createProjectExistsModelFromDiscriminatorValue, createProjectModelFromDiscriminatorValue, createUnhandledExceptionModelFromDiscriminatorValue, serializeCreateProjectModel, serializeProjectModel, type CreateProjectModel, type ProblemDetails, type ProjectExistsModel, type ProjectModel, type UnhandledExceptionModel } from '../models/index.js';
// @ts-ignore
import { AllRequestBuilderRequestsMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { ProjectsItemRequestBuilderRequestsMetadata, type ProjectsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /projects
 */
export interface ProjectsRequestBuilder extends BaseRequestBuilder<ProjectsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * Gets an item from the ticketTracer.Client.projects.item collection
     * @param id Unique identifier of the item
     * @returns {ProjectsItemRequestBuilder}
     */
     byId(id: Guid) : ProjectsItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProjectModel>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProjectExistsModel} error when the service returns a 409 status code
     * @throws {UnhandledExceptionModel} error when the service returns a 500 status code
     */
     post(body: CreateProjectModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProjectModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateProjectModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProjectsRequestBuilderUriTemplate = "{+baseurl}/projects";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProjectsRequestBuilderNavigationMetadata: Record<Exclude<keyof ProjectsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ProjectsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        requestsMetadata: AllRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProjectsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ProjectsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createProjectExistsModelFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createUnhandledExceptionModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createProjectModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateProjectModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
