/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBoardExistsModelFromDiscriminatorValue, createBoardModelFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, createProjectNotFoundModelFromDiscriminatorValue, createUnhandledExceptionModelFromDiscriminatorValue, serializeBoardModel, serializeCreateBoardModel, type BoardExistsModel, type BoardModel, type CreateBoardModel, type ProblemDetails, type ProjectNotFoundModel, type UnhandledExceptionModel } from '../models/index.js';
// @ts-ignore
import { AllRequestBuilderRequestsMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { AllByProjectRequestBuilderRequestsMetadata, type AllByProjectRequestBuilder } from './allByProject/index.js';
// @ts-ignore
import { BoardsItemRequestBuilderRequestsMetadata, type BoardsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /boards
 */
export interface BoardsRequestBuilder extends BaseRequestBuilder<BoardsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The allByProject property
     */
    get allByProject(): AllByProjectRequestBuilder;
    /**
     * Gets an item from the ticketTracer.Client.boards.item collection
     * @param id Unique identifier of the item
     * @returns {BoardsItemRequestBuilder}
     */
     byId(id: Guid) : BoardsItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BoardModel>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProjectNotFoundModel} error when the service returns a 404 status code
     * @throws {BoardExistsModel} error when the service returns a 409 status code
     * @throws {UnhandledExceptionModel} error when the service returns a 500 status code
     */
     post(body: CreateBoardModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BoardModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateBoardModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BoardsRequestBuilderUriTemplate = "{+baseurl}/boards";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BoardsRequestBuilderNavigationMetadata: Record<Exclude<keyof BoardsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: BoardsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        requestsMetadata: AllRequestBuilderRequestsMetadata,
    },
    allByProject: {
        requestsMetadata: AllByProjectRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BoardsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BoardsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProjectNotFoundModelFromDiscriminatorValue as ParsableFactory<Parsable>,
            409: createBoardExistsModelFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createUnhandledExceptionModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBoardModelFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateBoardModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
