/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBoardModelFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, createUnhandledExceptionModelFromDiscriminatorValue, type BoardModel, type ProblemDetails, type UnhandledExceptionModel } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /boards/{id}
 */
export interface BoardsItemRequestBuilder extends BaseRequestBuilder<BoardsItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BoardModel>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {UnhandledExceptionModel} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<BoardsItemRequestBuilderGetQueryParameters> | undefined) : Promise<BoardModel | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<BoardsItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface BoardsItemRequestBuilderGetQueryParameters {
    id?: Guid;
}
/**
 * Uri template for the request builder.
 */
export const BoardsItemRequestBuilderUriTemplate = "{+baseurl}/boards/{id}?id={id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const BoardsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BoardsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createUnhandledExceptionModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBoardModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
