/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createTicketModelFromDiscriminatorValue, createUnhandledExceptionModelFromDiscriminatorValue, type ProblemDetails, type TicketModel, type UnhandledExceptionModel } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /tickets/all-by-board
 */
export interface AllByBoardRequestBuilder extends BaseRequestBuilder<AllByBoardRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TicketModel[]>}
     * @throws {ProblemDetails} error when the service returns a 401 status code
     * @throws {ProblemDetails} error when the service returns a 403 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {UnhandledExceptionModel} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<AllByBoardRequestBuilderGetQueryParameters> | undefined) : Promise<TicketModel[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AllByBoardRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface AllByBoardRequestBuilderGetQueryParameters {
    boardId?: Guid;
    limit?: number;
    offset?: number;
}
/**
 * Uri template for the request builder.
 */
export const AllByBoardRequestBuilderUriTemplate = "{+baseurl}/tickets/all-by-board?boardId={boardId}{&limit*,offset*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const AllByBoardRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AllByBoardRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            403: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createUnhandledExceptionModelFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTicketModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
